### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by mProjectsCode** [mProjectsCode/obsidian-stats#3]
- [ ] Theme Download Stats
- [ ] Theme Release Stats
- [ ] Plugin and Theme Release timing Charts (maybe the data is not good enough for that)
- [ ] Author Pages?
- [ ] Clone every repo and extract data
  - [ ] Git Tags (Releases)
  - [ ] Number of src files
  - [ ] Lines of code?
  - [ ] has beta manifest
  - [ ] Dependencies (testing frameworks)

**Comment by mProjectsCode** [comment]
Hall of fame where top 5 plugins of specific statistics are shown

**Comment by 4Source** [comment]
Plugin Stats > Download stats 
2 extra graphs like "Plugin Downloads Correlations" but with "downloads vs issues" and "downloads vs open issues"
Does this project allow creating pull requests with changes?
